version: '3.8'

services:
  autoforwarderApi:
    image: autoforwarder/master:autoforwarder
    build:
      context: ./src/AutoForwarder.Api
      dockerfile: Dockerfile
    restart: always
    labels:
      NAME: "Auto Forwarder"
    networks:
      - app_network
    ports:
      - "5252:5252"

networks:
  app_network:
    driver: bridge
